package org.worldbank.connector;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class Connector
{
	private Connection con;
	private String username;
	private String password;
	private String host;
	private String port;

	public Connector(String username, String password, String host, String port)
	{
		this.username = username;
		this.password = password;
		this.host = host;
		this.port = port;
	}

	public void connect() throws ClassNotFoundException, SQLException
	{
		Class.forName("com.mysql.jdbc.Driver");
		String url = "jdbc:mysql://" + host + ":" + port + "/mysql";
		this.con = DriverManager.getConnection(url, username, password);
	}

	public boolean execute(String sql) throws SQLException
	{
		Statement stmt = con.createStatement();
		return stmt.execute(sql);

	}

	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException
	{
		Statement stmt = con.createStatement();
		return stmt.execute(sql, autoGeneratedKeys);
	}

	public boolean execute(String sql, int[] columnNames) throws SQLException
	{
		Statement stmt = con.createStatement();
		return stmt.execute(sql, columnNames);
	}

	public ResultSet executeQuery(String sql) throws SQLException
	{
		Statement stmt = con.createStatement();
		return stmt.executeQuery(sql);
	}

	public int executeUpdate(String sql) throws SQLException
	{
		Statement stmt = con.createStatement();
		return stmt.executeUpdate(sql);
	}

}

/*
 * public Connection getConnection() throws SQLException { Connection conn = null; Properties connectionProps = new
 * Properties(); connectionProps.put("user", this.username); connectionProps.put("password", this.password); if
 * (this.dbms.equals("mysql")) { conn = DriverManager.getConnection( "jdbc:" + this.dbms + "://" + this.serverName + ":"
 * + this.portNumber + "/", connectionProps); } System.out.println("Connected to database"); return conn; } public
 * static void main (String [] args) { try { Class.forName(��); //Or any other driver } catch(Exception x) {
 * System.out.println( �Unable to load the driver class!� ); } } }
 */