package org.worldbank.connector;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.worldbank.constants.SQLConstants;

public class Connector
{
	private static Logger log = LoggerFactory.getLogger(Connector.class);
	private Connection con;
	private String username;
	private String password;
	private String host;
	private String port;

	public Connector(String username, String password, String host, String port)
	{
		this.username = username;
		this.password = password;
		this.host = host;
		this.port = port;
	}

	public void connect() throws ClassNotFoundException, SQLException
	{
		log.info("Connecting to SQL. username:"+username+" host:"+host+" port:"+port);
		Class.forName("com.mysql.jdbc.Driver");
		String url = "jdbc:mysql://" + host + ":" + port + "/"+SQLConstants.getDatabaseName();
		this.con = DriverManager.getConnection(url, username, password);
	}

	public boolean execute(String sql) throws SQLException
	{
		Statement stmt = con.createStatement();
		return stmt.execute(sql);

	}

	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException
	{
		Statement stmt = con.createStatement();
		return stmt.execute(sql, autoGeneratedKeys);
	}

	public boolean execute(String sql, int[] columnNames) throws SQLException
	{
		Statement stmt = con.createStatement();
		return stmt.execute(sql, columnNames);
	}

	public ResultSet executeQuery(String sql) throws SQLException
	{
		Statement stmt = con.createStatement();
		return stmt.executeQuery(sql);
	}

	public int executeUpdate(String sql) throws SQLException
	{
		Statement stmt = con.createStatement();
		return stmt.executeUpdate(sql);
	}

}